// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// inverse_logit
NumericMatrix inverse_logit(NumericMatrix input, double param1, double param2);
RcppExport SEXP _xsdm_inverse_logit(SEXP inputSEXP, SEXP param1SEXP, SEXP param2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< double >::type param1(param1SEXP);
    Rcpp::traits::input_parameter< double >::type param2(param2SEXP);
    rcpp_result_gen = Rcpp::wrap(inverse_logit(input, param1, param2));
    return rcpp_result_gen;
END_RCPP
}
// bernoulli_lpmf
NumericVector bernoulli_lpmf(NumericVector x, NumericVector y);
RcppExport SEXP _xsdm_bernoulli_lpmf(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(bernoulli_lpmf(x, y));
    return rcpp_result_gen;
END_RCPP
}
// meanRow
NumericMatrix meanRow(NumericMatrix mat);
RcppExport SEXP _xsdm_meanRow(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(meanRow(mat));
    return rcpp_result_gen;
END_RCPP
}
// parallelVectorSum
double parallelVectorSum(NumericVector x);
RcppExport SEXP _xsdm_parallelVectorSum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(parallelVectorSum(x));
    return rcpp_result_gen;
END_RCPP
}
// response
NumericMatrix response(NumericMatrix x, double param1, double param2, double param3);
RcppExport SEXP _xsdm_response(SEXP xSEXP, SEXP param1SEXP, SEXP param2SEXP, SEXP param3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type param1(param1SEXP);
    Rcpp::traits::input_parameter< double >::type param2(param2SEXP);
    Rcpp::traits::input_parameter< double >::type param3(param3SEXP);
    rcpp_result_gen = Rcpp::wrap(response(x, param1, param2, param3));
    return rcpp_result_gen;
END_RCPP
}
// response_halfsquare
NumericMatrix response_halfsquare(NumericMatrix x);
RcppExport SEXP _xsdm_response_halfsquare(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(response_halfsquare(x));
    return rcpp_result_gen;
END_RCPP
}
// response_multi
NumericMatrix response_multi(NumericMatrix x, NumericVector sigl, NumericVector sigr);
RcppExport SEXP _xsdm_response_multi(SEXP xSEXP, SEXP siglSEXP, SEXP sigrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigl(siglSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigr(sigrSEXP);
    rcpp_result_gen = Rcpp::wrap(response_multi(x, sigl, sigr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xsdm_inverse_logit", (DL_FUNC) &_xsdm_inverse_logit, 3},
    {"_xsdm_bernoulli_lpmf", (DL_FUNC) &_xsdm_bernoulli_lpmf, 2},
    {"_xsdm_meanRow", (DL_FUNC) &_xsdm_meanRow, 1},
    {"_xsdm_parallelVectorSum", (DL_FUNC) &_xsdm_parallelVectorSum, 1},
    {"_xsdm_response", (DL_FUNC) &_xsdm_response, 4},
    {"_xsdm_response_halfsquare", (DL_FUNC) &_xsdm_response_halfsquare, 1},
    {"_xsdm_response_multi", (DL_FUNC) &_xsdm_response_multi, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_xsdm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
