// Generated by rstantools.  Do not edit by hand.

/*
    xsdm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    xsdm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with xsdm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_lewontin_cohen_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 85> locations_array__ =
  {" (found before start of program)",
  " (in 'lewontin_cohen', line 10, column 2 to column 15)",
  " (in 'lewontin_cohen', line 11, column 2 to column 26)",
  " (in 'lewontin_cohen', line 12, column 2 to column 26)",
  " (in 'lewontin_cohen', line 13, column 2 to column 28)",
  " (in 'lewontin_cohen', line 16, column 2 to column 9)",
  " (in 'lewontin_cohen', line 17, column 2 to column 27)",
  " (in 'lewontin_cohen', line 52, column 2 to column 16)",
  " (in 'lewontin_cohen', line 53, column 2 to column 20)",
  " (in 'lewontin_cohen', line 55, column 11 to column 12)",
  " (in 'lewontin_cohen', line 55, column 4 to column 23)",
  " (in 'lewontin_cohen', line 56, column 11 to column 12)",
  " (in 'lewontin_cohen', line 56, column 4 to column 21)",
  " (in 'lewontin_cohen', line 57, column 11 to column 12)",
  " (in 'lewontin_cohen', line 57, column 4 to column 16)",
  " (in 'lewontin_cohen', line 58, column 11 to column 12)",
  " (in 'lewontin_cohen', line 58, column 4 to column 16)",
  " (in 'lewontin_cohen', line 59, column 11 to column 12)",
  " (in 'lewontin_cohen', line 59, column 4 to column 16)",
  " (in 'lewontin_cohen', line 64, column 8 to column 33)",
  " (in 'lewontin_cohen', line 65, column 8 to column 44)",
  " (in 'lewontin_cohen', line 70, column 12 to column 40)",
  " (in 'lewontin_cohen', line 69, column 15 to line 71, column 11)",
  " (in 'lewontin_cohen', line 68, column 12 to column 40)",
  " (in 'lewontin_cohen', line 67, column 24 to line 69, column 9)",
  " (in 'lewontin_cohen', line 67, column 10 to line 71, column 11)",
  " (in 'lewontin_cohen', line 66, column 22 to line 72, column 9)",
  " (in 'lewontin_cohen', line 66, column 8 to line 72, column 9)",
  " (in 'lewontin_cohen', line 73, column 8 to column 36)",
  " (in 'lewontin_cohen', line 63, column 19 to line 74, column 7)",
  " (in 'lewontin_cohen', line 63, column 6 to line 74, column 7)",
  " (in 'lewontin_cohen', line 75, column 6 to column 33)",
  " (in 'lewontin_cohen', line 76, column 6 to column 74)",
  " (in 'lewontin_cohen', line 62, column 17 to line 77, column 5)",
  " (in 'lewontin_cohen', line 62, column 4 to line 77, column 5)",
  " (in 'lewontin_cohen', line 53, column 20 to line 78, column 3)",
  " (in 'lewontin_cohen', line 79, column 2 to column 13)",
  " (in 'lewontin_cohen', line 21, column 9 to column 10)",
  " (in 'lewontin_cohen', line 21, column 2 to column 21)",
  " (in 'lewontin_cohen', line 22, column 9 to column 10)",
  " (in 'lewontin_cohen', line 22, column 2 to column 19)",
  " (in 'lewontin_cohen', line 23, column 9 to column 10)",
  " (in 'lewontin_cohen', line 23, column 2 to column 14)",
  " (in 'lewontin_cohen', line 24, column 9 to column 10)",
  " (in 'lewontin_cohen', line 24, column 2 to column 14)",
  " (in 'lewontin_cohen', line 25, column 9 to column 10)",
  " (in 'lewontin_cohen', line 25, column 2 to column 14)",
  " (in 'lewontin_cohen', line 27, column 2 to column 21)",
  " (in 'lewontin_cohen', line 28, column 2 to column 26)",
  " (in 'lewontin_cohen', line 29, column 2 to column 26)",
  " (in 'lewontin_cohen', line 30, column 2 to column 20)",
  " (in 'lewontin_cohen', line 31, column 2 to column 21)",
  " (in 'lewontin_cohen', line 32, column 2 to column 29)",
  " (in 'lewontin_cohen', line 36, column 6 to column 31)",
  " (in 'lewontin_cohen', line 37, column 6 to column 42)",
  " (in 'lewontin_cohen', line 42, column 10 to column 38)",
  " (in 'lewontin_cohen', line 41, column 13 to line 43, column 9)",
  " (in 'lewontin_cohen', line 40, column 10 to column 38)",
  " (in 'lewontin_cohen', line 39, column 22 to line 41, column 7)",
  " (in 'lewontin_cohen', line 39, column 8 to line 43, column 9)",
  " (in 'lewontin_cohen', line 38, column 20 to line 44, column 7)",
  " (in 'lewontin_cohen', line 38, column 6 to line 44, column 7)",
  " (in 'lewontin_cohen', line 45, column 6 to column 34)",
  " (in 'lewontin_cohen', line 35, column 17 to line 46, column 5)",
  " (in 'lewontin_cohen', line 35, column 4 to line 46, column 5)",
  " (in 'lewontin_cohen', line 47, column 4 to column 31)",
  " (in 'lewontin_cohen', line 34, column 15 to line 48, column 3)",
  " (in 'lewontin_cohen', line 34, column 2 to line 48, column 3)",
  " (in 'lewontin_cohen', line 49, column 2 to column 46)",
  " (in 'lewontin_cohen', line 2, column 2 to column 8)",
  " (in 'lewontin_cohen', line 3, column 2 to column 8)",
  " (in 'lewontin_cohen', line 4, column 2 to column 8)",
  " (in 'lewontin_cohen', line 5, column 8 to column 9)",
  " (in 'lewontin_cohen', line 5, column 2 to column 36)",
  " (in 'lewontin_cohen', line 6, column 8 to column 9)",
  " (in 'lewontin_cohen', line 6, column 10 to column 11)",
  " (in 'lewontin_cohen', line 6, column 12 to column 13)",
  " (in 'lewontin_cohen', line 6, column 2 to column 23)",
  " (in 'lewontin_cohen', line 10, column 9 to column 10)",
  " (in 'lewontin_cohen', line 11, column 18 to column 19)",
  " (in 'lewontin_cohen', line 12, column 18 to column 19)",
  " (in 'lewontin_cohen', line 13, column 23 to column 24)",
  " (in 'lewontin_cohen', line 52, column 9 to column 10)",
  " (in 'lewontin_cohen', line 52, column 11 to column 12)",
  " (in 'lewontin_cohen', line 53, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_lewontin_cohen final : public model_base_crtp<model_lewontin_cohen> {
private:
  int N;
  int M;
  int P;
  std::vector<int> occ;
  std::vector<std::vector<std::vector<double>>> ts;
public:
  ~model_lewontin_cohen() {}
  model_lewontin_cohen(stan::io::var_context& context__, unsigned int
                       random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_lewontin_cohen_namespace::model_lewontin_cohen";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 69;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 69;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 70;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 70;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 71;
      context__.validate_dims("data initialization", "P", "int",
        std::vector<size_t>{});
      P = std::numeric_limits<int>::min();
      current_statement__ = 71;
      P = context__.vals_i("P")[(1 - 1)];
      current_statement__ = 72;
      stan::math::validate_non_negative_index("occ", "N", N);
      current_statement__ = 73;
      context__.validate_dims("data initialization", "occ", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      occ = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 73;
      occ = context__.vals_i("occ");
      current_statement__ = 73;
      stan::math::check_greater_or_equal(function__, "occ", occ, 0);
      current_statement__ = 73;
      stan::math::check_less_or_equal(function__, "occ", occ, 1);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("ts", "N", N);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("ts", "M", M);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("ts", "P", P);
      current_statement__ = 77;
      context__.validate_dims("data initialization", "ts", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(M),
          static_cast<size_t>(P)});
      ts = std::vector<std::vector<std::vector<double>>>(N,
             std::vector<std::vector<double>>(M,
               std::vector<double>(P,
                 std::numeric_limits<double>::quiet_NaN())));
      {
        std::vector<local_scalar_t__> ts_flat__;
        current_statement__ = 77;
        ts_flat__ = context__.vals_r("ts");
        current_statement__ = 77;
        pos__ = 1;
        current_statement__ = 77;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          current_statement__ = 77;
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            current_statement__ = 77;
            for (int sym3__ = 1; sym3__ <= N; ++sym3__) {
              current_statement__ = 77;
              stan::model::assign(ts, ts_flat__[(pos__ - 1)],
                "assigning variable ts", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 77;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 78;
      stan::math::validate_non_negative_index("mu", "P", P);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("sigl", "P", P);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("sigr", "P", P);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("L", "P", P);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("L", "P", P);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("R", "P", P);
      current_statement__ = 83;
      stan::math::validate_non_negative_index("R", "P", P);
      current_statement__ = 84;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = P + P + P + ((P * (P - 1)) / 2) + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_lewontin_cohen";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_lewontin_cohen_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 1;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(P);
      Eigen::Matrix<local_scalar_t__,-1,1> sigl =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 2;
      sigl = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, P);
      Eigen::Matrix<local_scalar_t__,-1,1> sigr =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 3;
      sigr = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, P);
      Eigen::Matrix<local_scalar_t__,-1,-1> L =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(P, P, DUMMY_VAR__);
      current_statement__ = 4;
      L = in__.template read_constrain_cholesky_factor_corr<
            Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(lp__, P);
      local_scalar_t__ c = DUMMY_VAR__;
      current_statement__ = 5;
      c = in__.template read<local_scalar_t__>();
      local_scalar_t__ pd = DUMMY_VAR__;
      current_statement__ = 6;
      pd = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
             1, lp__);
      {
        current_statement__ = 37;
        stan::math::validate_non_negative_index("response", "M", M);
        Eigen::Matrix<local_scalar_t__,-1,1> response =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
        current_statement__ = 39;
        stan::math::validate_non_negative_index("loglam", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> loglam =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 41;
        stan::math::validate_non_negative_index("u", "P", P);
        Eigen::Matrix<local_scalar_t__,-1,1> u =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
        current_statement__ = 43;
        stan::math::validate_non_negative_index("v", "P", P);
        Eigen::Matrix<local_scalar_t__,-1,1> v =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
        current_statement__ = 45;
        stan::math::validate_non_negative_index("w", "P", P);
        Eigen::Matrix<local_scalar_t__,-1,1> w =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
        current_statement__ = 47;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, 0, 10));
        current_statement__ = 48;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigl, 0.1));
        current_statement__ = 49;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigr, 0.1));
        current_statement__ = 50;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(c, 0, 10));
        current_statement__ = 51;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(pd, 0, 1));
        current_statement__ = 52;
        lp_accum__.add(stan::math::lkj_corr_cholesky_lpdf<propto__>(L, 2.0));
        current_statement__ = 67;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 64;
          for (int j = 1; j <= M; ++j) {
            current_statement__ = 53;
            stan::model::assign(w,
              stan::math::to_vector(
                stan::model::rvalue(ts, "ts", stan::model::index_uni(i),
                  stan::model::index_uni(j), stan::model::index_omni())),
              "assigning variable w");
            current_statement__ = 54;
            stan::model::assign(u,
              stan::math::mdivide_left_tri_low(L, stan::math::subtract(w, mu)),
              "assigning variable u");
            current_statement__ = 61;
            for (int k = 1; k <= P; ++k) {
              current_statement__ = 59;
              if (stan::math::logical_lt(
                    stan::model::rvalue(u, "u", stan::model::index_uni(k)), 0)) {
                current_statement__ = 57;
                stan::model::assign(v,
                  stan::math::pow(
                    (stan::model::rvalue(u, "u", stan::model::index_uni(k)) /
                    stan::model::rvalue(sigl, "sigl",
                      stan::model::index_uni(k))), 2),
                  "assigning variable v", stan::model::index_uni(k));
              } else {
                current_statement__ = 55;
                stan::model::assign(v,
                  stan::math::pow(
                    (stan::model::rvalue(u, "u", stan::model::index_uni(k)) /
                    stan::model::rvalue(sigr, "sigr",
                      stan::model::index_uni(k))), 2),
                  "assigning variable v", stan::model::index_uni(k));
              }
            }
            current_statement__ = 62;
            stan::model::assign(response, (-0.5 * stan::math::sum(v)),
              "assigning variable response", stan::model::index_uni(j));
          }
          current_statement__ = 65;
          stan::model::assign(loglam, stan::math::mean(response),
            "assigning variable loglam", stan::model::index_uni(i));
        }
        current_statement__ = 68;
        lp_accum__.add(stan::math::bernoulli_lpmf<propto__>(occ,
                         stan::math::multiply(pd,
                           stan::math::inv_logit(
                             stan::math::subtract(loglam, c)))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_lewontin_cohen_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(P,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(P);
      Eigen::Matrix<double,-1,1> sigl =
        Eigen::Matrix<double,-1,1>::Constant(P,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      sigl = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, P);
      Eigen::Matrix<double,-1,1> sigr =
        Eigen::Matrix<double,-1,1>::Constant(P,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      sigr = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, P);
      Eigen::Matrix<double,-1,-1> L =
        Eigen::Matrix<double,-1,-1>::Constant(P, P,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      L = in__.template read_constrain_cholesky_factor_corr<
            Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(lp__, P);
      double c = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      c = in__.template read<local_scalar_t__>();
      double pd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      pd = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
             1, lp__);
      out__.write(mu);
      out__.write(sigl);
      out__.write(sigr);
      out__.write(L);
      out__.write(c);
      out__.write(pd);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,-1> R =
        Eigen::Matrix<double,-1,-1>::Constant(P, P,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      {
        current_statement__ = 9;
        stan::math::validate_non_negative_index("response", "M", M);
        Eigen::Matrix<double,-1,1> response =
          Eigen::Matrix<double,-1,1>::Constant(M,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 11;
        stan::math::validate_non_negative_index("loglam", "N", N);
        Eigen::Matrix<double,-1,1> loglam =
          Eigen::Matrix<double,-1,1>::Constant(N,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 13;
        stan::math::validate_non_negative_index("u", "P", P);
        Eigen::Matrix<double,-1,1> u =
          Eigen::Matrix<double,-1,1>::Constant(P,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 15;
        stan::math::validate_non_negative_index("v", "P", P);
        Eigen::Matrix<double,-1,1> v =
          Eigen::Matrix<double,-1,1>::Constant(P,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 17;
        stan::math::validate_non_negative_index("w", "P", P);
        Eigen::Matrix<double,-1,1> w =
          Eigen::Matrix<double,-1,1>::Constant(P,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 34;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 30;
          for (int j = 1; j <= M; ++j) {
            current_statement__ = 19;
            stan::model::assign(w,
              stan::math::to_vector(
                stan::model::rvalue(ts, "ts", stan::model::index_uni(i),
                  stan::model::index_uni(j), stan::model::index_omni())),
              "assigning variable w");
            current_statement__ = 20;
            stan::model::assign(u,
              stan::math::mdivide_left_tri_low(L, stan::math::subtract(w, mu)),
              "assigning variable u");
            current_statement__ = 27;
            for (int k = 1; k <= P; ++k) {
              current_statement__ = 25;
              if (stan::math::logical_lt(
                    stan::model::rvalue(u, "u", stan::model::index_uni(k)), 0)) {
                current_statement__ = 23;
                stan::model::assign(v,
                  stan::math::pow(
                    (stan::model::rvalue(u, "u", stan::model::index_uni(k)) /
                    stan::model::rvalue(sigl, "sigl",
                      stan::model::index_uni(k))), 2),
                  "assigning variable v", stan::model::index_uni(k));
              } else {
                current_statement__ = 21;
                stan::model::assign(v,
                  stan::math::pow(
                    (stan::model::rvalue(u, "u", stan::model::index_uni(k)) /
                    stan::model::rvalue(sigr, "sigr",
                      stan::model::index_uni(k))), 2),
                  "assigning variable v", stan::model::index_uni(k));
              }
            }
            current_statement__ = 28;
            stan::model::assign(response, (-0.5 * stan::math::sum(v)),
              "assigning variable response", stan::model::index_uni(j));
          }
          current_statement__ = 31;
          stan::model::assign(loglam, stan::math::mean(response),
            "assigning variable loglam", stan::model::index_uni(i));
          current_statement__ = 32;
          stan::model::assign(log_lik,
            stan::math::bernoulli_lpmf<false>(
              stan::model::rvalue(occ, "occ", stan::model::index_uni(i)), (pd
              *
              stan::math::inv_logit(
                (stan::model::rvalue(loglam, "loglam",
                   stan::model::index_uni(i)) - c)))),
            "assigning variable log_lik", stan::model::index_uni(i));
        }
      }
      current_statement__ = 36;
      stan::model::assign(R,
        stan::math::multiply(L, stan::math::transpose(L)),
        "assigning variable R");
      out__.write(R);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(P),
        "assigning variable mu");
      out__.write(mu);
      Eigen::Matrix<local_scalar_t__,-1,1> sigl =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(sigl,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(P),
        "assigning variable sigl");
      out__.write_free_lb(0, sigl);
      Eigen::Matrix<local_scalar_t__,-1,1> sigr =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(sigr,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(P),
        "assigning variable sigr");
      out__.write_free_lb(0, sigr);
      Eigen::Matrix<local_scalar_t__,-1,-1> L =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(P, P, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(L,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(P, P),
        "assigning variable L");
      out__.write_free_cholesky_factor_corr(L);
      local_scalar_t__ c = DUMMY_VAR__;
      current_statement__ = 5;
      c = in__.read<local_scalar_t__>();
      out__.write(c);
      local_scalar_t__ pd = DUMMY_VAR__;
      current_statement__ = 6;
      pd = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, pd);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{static_cast<size_t>(P)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigl", "double",
        std::vector<size_t>{static_cast<size_t>(P)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sigr", "double",
        std::vector<size_t>{static_cast<size_t>(P)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "L", "double",
        std::vector<size_t>{static_cast<size_t>(P), static_cast<size_t>(P)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "c", "double",
        std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "pd", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 1;
        mu_flat__ = context__.vals_r("mu");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(mu, mu_flat__[(pos__ - 1)],
            "assigning variable mu", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(mu);
      Eigen::Matrix<local_scalar_t__,-1,1> sigl =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigl_flat__;
        current_statement__ = 2;
        sigl_flat__ = context__.vals_r("sigl");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(sigl, sigl_flat__[(pos__ - 1)],
            "assigning variable sigl", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigl);
      Eigen::Matrix<local_scalar_t__,-1,1> sigr =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigr_flat__;
        current_statement__ = 3;
        sigr_flat__ = context__.vals_r("sigr");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(sigr, sigr_flat__[(pos__ - 1)],
            "assigning variable sigr", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigr);
      Eigen::Matrix<local_scalar_t__,-1,-1> L =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(P, P, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> L_flat__;
        current_statement__ = 4;
        L_flat__ = context__.vals_r("L");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
            current_statement__ = 4;
            stan::model::assign(L, L_flat__[(pos__ - 1)],
              "assigning variable L", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 4;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_cholesky_factor_corr(L);
      local_scalar_t__ c = DUMMY_VAR__;
      current_statement__ = 5;
      c = context__.vals_r("c")[(1 - 1)];
      out__.write(c);
      local_scalar_t__ pd = DUMMY_VAR__;
      current_statement__ = 6;
      pd = context__.vals_r("pd")[(1 - 1)];
      out__.write_free_lub(0, 1, pd);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "sigl", "sigr", "L", "c", "pd"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"R", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(P)},
                std::vector<size_t>{static_cast<size_t>(P)},
                std::vector<size_t>{static_cast<size_t>(P)},
                std::vector<size_t>{static_cast<size_t>(P),
                  static_cast<size_t>(P)}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(P),
               static_cast<size_t>(P)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigl" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigr" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
        param_names__.emplace_back(std::string() + "L" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "c");
    param_names__.emplace_back(std::string() + "pd");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
          param_names__.emplace_back(std::string() + "R" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigl" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigr" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= ((P * (P - 1)) / 2); ++sym1__) {
      param_names__.emplace_back(std::string() + "L" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "c");
    param_names__.emplace_back(std::string() + "pd");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
          param_names__.emplace_back(std::string() + "R" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"sigl\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"sigr\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(P) + ",\"cols\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"pd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"R\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(P) + ",\"cols\":" + std::to_string(P) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"sigl\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"sigr\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(((P * (P - 1)) /2)) + "},\"block\":\"parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"pd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"R\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(P) + ",\"cols\":" + std::to_string(P) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((P + P) + P) + (P * P)) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (((P * P) +
      N));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((P + P) + P) + (P * P)) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (((P * P) +
      N));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_lewontin_cohen_namespace::model_lewontin_cohen;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_lewontin_cohen_namespace::profiles__;
}
#endif
#endif
