# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.response <- function(x, param1, param2, param3) {
    .Call(`_xsdm_response`, x, param1, param2, param3)
}

