# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.invLogit <- function(input, param1, param2) {
    .Call(`_xsdm_inverse_logit`, input, param1, param2)
}

.meanRow <- function(mat) {
    .Call(`_xsdm_meanRow`, mat)
}

.response <- function(x, param1, param2, param3) {
    .Call(`_xsdm_response`, x, param1, param2, param3)
}

